-- Smangsty: Do not register a global UI rebuild hotkey here.
-- Ctrl+R is a normal gameplay chord (for example aim + reload) and rebuilding
-- player UI from a gameplay keypress can invalidate live inventory/UI state.
-- Keep UI rebuild actions explicit inside developer tooling instead.
